# Site wide configuration

title: Marine Biodiversity Observation Network
image:
  feature: feature-image-kelp.JPG
description: With 13 scientific investigators and 10 partner institutions, the marine biodiversity observation network (MBON) centered on the Santa Barbara Channel is the epitome of collaboration.logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //bdoheny.github.io/MBON_skinnybones

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Brandon Doheny
  web: 
  email: 
  twitter: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: 
    ad-client: 
    ad-slot: 
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
